### ISSUE TITLE
转换后没有输出文件

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [hihkm/DanmakuFactory#10]
win10，版本1.51
~~又是我，别打我（小声）~~
发现可能在转换一些比较大（大概15mb+）的xml文件会出现无输出但是又无报错的情况，尽管尝试了拆分xml文件为比较小的多个分批转换，但是也出现了以上的情况，不知道为什么。。

**Comment by hihkm** [comment]
可以提供一下出问题`xml`文件嘛，邮箱的话可以发到`hkm@tikm.org`

**Comment by leecoooo** [comment]
我也出现这个问题，跟文件没有关系，重启电脑后再转换就好了

**Comment by hihkm** [comment]
@leecoooo @Uc207Pr4f57t9-251 问题已修复，请下载最新版本〒▽〒
