### ISSUE TITLE
不同分辨率下渲染 SC 位置错误

### ISSUE THREAD

**Issue by timerring** [hihkm/DanmakuFactory#101]
b 站不同直播间开播的分辨率都不一样，大概有以下几种类型：
+ (width=1600, height=1280)
+ (width=1920, height=1080)
+ (width=1080, height=1920)
+ (width=1280, height=720)
+ (width=720, height=1280)

**如果使用 `-r` 指定分辨率参数的形式，则会造成 SC 渲染的失败**。
例如，通常一个视频的弹幕转换后默认情况下是 1920x1080 分辨率，渲染在 1280x720 的视频没有问题，但是如果指定参数例如 `-r 1280x720` 则在 1280x720 的视频中渲染不出 sc，已知原因是位置参数的错误，SC 默认是左下角为起点，向右为正 x 轴，向下为正 y 轴，必须要将 y 轴置为负才能在画面中渲染出 SC。是否应该添加一些常见分辨率下的 SC 最佳渲染位置？

**Comment by timerring** [comment]
这是我摸索出来 1280x720 分辨率的弹幕在 1280x720 分辨率的视频中最佳渲染位置 `--msgboxpos 0x-365` 其中 x 轴为 0，y 轴为-365。

**Comment by lengyanyu258** [comment]
关于 SC 消息框位置的设置，参考此图：
https://github.com/hihkm/DanmakuFactory/blob/master/VBGUI/DanmakuFactory/Resources/messageSetting.png
![messageSetting](https://github.com/user-attachments/assets/2770f753-fa82-4f5a-bb96-c7d869806998)
其中 (X, Y) 原点位于左上角，对应 msgboxpos 的参数，消息框的宽和高对应于 msgboxsize 的参数，请确认您的参数使用是否正确？

**Comment by timerring** [comment]
好的了解，一直用的 cli 处理没看到 gui 的文档。
