### ISSUE TITLE
非B站的xml弹幕文件是不是不支持转换？点转换后只有开头内容

### ISSUE THREAD

**Issue by wengchenxu** [hihkm/DanmakuFactory#12]
[Script Info]
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080
Timer: 100.0000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding

Style: R2L,Microsoft YaHei,38,&H37FFFFFF,&H00FFFFFF,&H00000000,&H1E6A5149,0,0,0,0,100.00,100.00,0.00,0.00,1,0,1,8,0,0,0,1
Style: L2R,Microsoft YaHei,38,&H37FFFFFF,&H00FFFFFF,&H00000000,&H1E6A5149,0,0,0,0,100.00,100.00,0.00,0.00,1,0,1,8,0,0,0,1
Style: TOP,Microsoft YaHei,38,&H37FFFFFF,&H00FFFFFF,&H00000000,&H1E6A5149,0,0,0,0,100.00,100.00,0.00,0.00,1,0,1,8,0,0,0,1
Style: BTM,Microsoft YaHei,38,&H37FFFFFF,&H00FFFFFF,&H00000000,&H1E6A5149,0,0,0,0,100.00,100.00,0.00,0.00,1,0,1,8,0,0,0,1
Style: SP,Microsoft YaHei,38,&H00FFFFFF,&H00FFFFFF,&H00000000,&H1E6A5149,0,0,0,0,100.00,100.00,0.00,0.00,1,0,1,7,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text

**Comment by hihkm** [comment]
是的，因为不同网站的弹幕格式都不尽相同，无法做到完全兼容。可以使用最新CLI版本的自定义输入模板功能进行转换。
