### ISSUE TITLE
转换后没有输出文件

### ISSUE THREAD

**Issue by mzada** [hihkm/DanmakuFactory#13]
今天在转换多个文件时发现转换后没有输出文件，同时也不报错。在尝试一个一个转后也遇到了一样的问题
其中最小的13k，最大的290k
多次尝试后发现转换效果很不稳定，一会儿能转（最多只能转一个，而且随机）一会儿不能
重启电脑也无效
个人猜测文件写入出了问题

出问题的文件：
[bin.zip](https://github.com/hihkm/DanmakuFactory/files/6136018/bin.zip)

**Comment by hihkm** [comment]
感谢反馈！这个问题正在极力排查修复(┬┬﹏┬┬)

**Comment by hihkm** [comment]
你好，可否帮忙测试一下这个问题是否仍然出现
[DanmakuFactory.zip](https://github.com/hihkm/DanmakuFactory/files/6136141/DanmakuFactory.zip)

**Comment by mzada** [comment]
好的，我现在在外面上课，回来后就来测试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月14日(周日) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hihkm/DanmakuFactory] 转换后没有输出文件 (#13)




 
你好，可否帮忙测试一下这个问题是否仍然出现
 DanmakuFactory.zip

**Comment by mzada** [comment]
你好，zip包已经解压了，但是无法运行程序
zip包内程序150kb，原程序430kb，有没有可能发错程序了？


Gliese
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hihkm/DanmakuFactory"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 中午1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hihkm/DanmakuFactory] 转换后没有输出文件 (#13)





 
你好，可否帮忙测试一下这个问题是否仍然出现
 DanmakuFactory.zip

**Comment by hihkm** [comment]
刚才那个不包含图形界面，试下这个
[DanmakuFactory.zip](https://github.com/hihkm/DanmakuFactory/files/6136480/DanmakuFactory.zip)

**Comment by mzada** [comment]
问题已解决（至少现在测试了6个文件，不管单独还是多个都没有问题）
谢谢




Gliese
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hihkm/DanmakuFactory"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hihkm/DanmakuFactory] 转换后没有输出文件 (#13)





 
刚才那个不包含图形界面，试下这个
 DanmakuFactory.zip

**Comment by hihkm** [comment]
好的，这个是非正式的版本，所以请关注一下后续的更新哦(*^_^*)
