### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by MrBeanc** [hihkm/DanmakuFactory#14]
你好，我在使用make命令编译文件时出现了错误
gcc -c JsonFile.c -o temp/json.o
gcc -c XmlFile.c -o temp/xml.o
gcc temp/main.o temp/string.o temp/list.o temp/config.o temp/template.o temp/ass.o temp/json.o temp/xml.o -o DanmakuFactory
/usr/bin/ld: temp/main.o: in function `main':
main.c:(.text+0xe2): undefined reference to `sprintf_s'
/usr/bin/ld: main.c:(.text+0x9d3): undefined reference to `sprintf_s'
/usr/bin/ld: temp/list.o: in function `sortList':
DanmakuFactoryList.c:(.text+0x215): undefined reference to `floor'
/usr/bin/ld: temp/template.o: in function `readTemplateFile':
TemplateFile.c:(.text+0x305): undefined reference to `sprintf_s'
/usr/bin/ld: TemplateFile.c:(.text+0x32d): undefined reference to `strcat_s'
/usr/bin/ld: TemplateFile.c:(.text+0x527): undefined reference to `strcat_s'
/usr/bin/ld: TemplateFile.c:(.text+0x9c3): undefined reference to `strcat_s'
/usr/bin/ld: TemplateFile.c:(.text+0xd1f): undefined reference to `strcat_s'
/usr/bin/ld: TemplateFile.c:(.text+0xd6f): undefined reference to `strcat_s'
/usr/bin/ld: temp/template.o:TemplateFile.c:(.text+0xe5d): more undefined references to `strcat_s' follow
collect2: error: ld returned 1 exit status
make: *** [makefile:5: DanmakuFactory] Error 1

**Comment by hihkm** [comment]
你好，是什么环境呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月29日(周一) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hihkm/DanmakuFactory] 编译时出现错误 (#14)




 
你好，我在使用make命令编译文件时出现了错误
 gcc -c JsonFile.c -o temp/json.o
 gcc -c XmlFile.c -o temp/xml.o
 gcc temp/main.o temp/string.o temp/list.o temp/config.o temp/template.o temp/ass.o temp/json.o temp/xml.o -o DanmakuFactory
 /usr/bin/ld: temp/main.o: in function main': main.c:(.text+0xe2): undefined reference to sprintf_s'
 /usr/bin/ld: main.c:(.text+0x9d3): undefined reference to sprintf_s' /usr/bin/ld: temp/list.o: in function sortList':
 DanmakuFactoryList.c:(.text+0x215): undefined reference to floor' /usr/bin/ld: temp/template.o: in function readTemplateFile':
 TemplateFile.c:(.text+0x305): undefined reference to sprintf_s' /usr/bin/ld: TemplateFile.c:(.text+0x32d): undefined reference to strcat_s'
 /usr/bin/ld: TemplateFile.c:(.text+0x527): undefined reference to strcat_s' /usr/bin/ld: TemplateFile.c:(.text+0x9c3): undefined reference to strcat_s'
 /usr/bin/ld: TemplateFile.c:(.text+0xd1f): undefined reference to strcat_s' /usr/bin/ld: TemplateFile.c:(.text+0xd6f): undefined reference to strcat_s'
 /usr/bin/ld: temp/template.o:TemplateFile.c:(.text+0xe5d): more undefined references to `strcat_s' follow
 collect2: error: ld returned 1 exit status
 make: *** [makefile:5: DanmakuFactory] Error 1

**Comment by MrBeanc** [comment]
ubuntu 18  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by hihkm** [comment]
好的 我晚点看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月29日(周一) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hihkm/DanmakuFactory] 编译时出现错误 (#14)




 
ubuntu 18  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by hihkm** [comment]
新加入的内容用了少量crt安全函数，导致无法在linux下编译通过，将尽快修正~

**Comment by hihkm** [comment]
问题已修复，请重新编译一下
