### ISSUE TITLE
想请问一下gui版本如何进行多文件合并

### ISSUE THREAD

**Issue by anrui12** [hihkm/DanmakuFactory#18]
界面里没有对应的选项，文档找了一圈似乎也没看到。只能在这提问了，不好意思

**Comment by anrui12** [comment]
噢，看了一下1.51里的详细文档，好像命令行才可以，暂时没问题了

**Comment by hihkm** [comment]
GUI版本暂时不支持，界面中的多文件是批量转换，如果再加入合并逻辑上可能会过于复杂。
- 可以手动或者用批处理合并文件再进行转换，头尾相接即可，没有很严格的格式要求。
- 更建议是命令行，其实也是比较简单的，也比较灵活，如果有很多这样的文件可以尝试写一个批处理。
- 如果涉及时间轴不统一，那必须使用命令行了。
有什么问题欢迎提问哦（虽然更新摸了好久） o(*￣▽￣*)ブ

**Comment by anrui12** [comment]
嗯嗯，后来我直接命令行合了。之前下载的GUI版里面没有详细文档，所以一直以为是自己哪里看漏，才来问的。后来找到v1.51的文档就好了
更新辛苦，加油哈
