### ISSUE TITLE
输出的ass文件没有对特殊字符进行处理

### ISSUE THREAD

**Issue by gin3715** [hihkm/DanmakuFactory#19]
弹幕文本在ass中会被转义的部分没有进行处理就直接输出了

比如XML弹幕`<d>\noa/\noa/\noa/</d>`会直接在ass中输出为`{\move(2270,1,-350,1)}\noa/\noa/\noa/\noa/`，其中应作为literal的`\n`会被字幕引擎作为处理为soft line break，需要输出为`{\move(2270,1,-350,1)}\{}noa/\{}noa/\{}noa/\{}noa/`防止`\n`被转义。

带`\n`的弹幕似乎不能发送至B站视频/直播回放，但存在于直播和直播录制的弹幕
带`\N`、`\h`以及`{`、`}`的弹幕都可以正常发送

另一种可能的处理方式是用全角字符进行替代，如用`｛ ｝`代替`{ }`。实际在aegisub 3.2.2中测试下来，没有很好的对花括号进行escape的方法，用全角字符代替可能是最佳方法。

**Comment by hihkm** [comment]
感谢反馈！换行和空格的处理会在下个版本实装（大概），花括号的问题我斟酌一下，用全角字符替换总感觉有点暴力了。
翻阅了ass和aegisub的文档，都没有给出相关的解释，ass好像没有字符转义的概念，都是通过一些技巧来防止样式代码被误解析，可能是个设计缺陷吧。
经过测试，`{`会一直往后匹配`}`，如果匹配成功，中间部分会被视为style override codes。如果匹配不成功似乎会被解析为`{`字符； 同理，没有被`{`匹配的`}`也会被视作一个字符，但没有办法通过这种方式覆盖全部情况orz。
