### ISSUE TITLE
能否加入弹幕文件合并功能

### ISSUE THREAD

**Issue by Gliese129** [hihkm/DanmakuFactory#21]
可不可以做到输入多个弹幕文件，输出一个合并后的弹幕文件。网上没有找到合适的弹幕合并程序（悲）

**Comment by hihkm** [comment]
你好，cli 版本带有此功能，但 gui 暂不支持。
一个简单的例子：
danmakufactory -i "input1.ass" "input2.xml" -o "output.ass"

此外还可以定义每个输入弹幕的时轴偏移量，详见打包内文档~
手机邮件回复，没有使用 markdown 格式比较混乱，见谅~
