### ISSUE TITLE
Superchat的message_box能否设置持续时间

### ISSUE THREAD

**Issue by lzy0702** [hihkm/DanmakuFactory#25]
发现message_box一直遮挡画面，能不能允许用户指定一个持续时间和消失方式（就近滑出画面或者渐隐什么的）？

**Comment by hihkm** [comment]
感谢建议！目前该项目正在重构，目的是提供更多自定义功能和解决一些问题。后续会加入更多礼物的显示形式~

**Comment by sieveLau** [comment]
PR #51 已实现该功能，建议close这个issue。
