### ISSUE TITLE
礼物价格显示问题

### ISSUE THREAD

**Issue by lanyuuuu** [hihkm/DanmakuFactory#29]
您好！今天在设置了礼物最低显示价格30元之后，还是出现了很多免费的礼物，辣条和PK票。但是这个问题在前天使用的时候并没有出现，设置价格之后是会按照价格进行显示的，这个算是bug吗？（使用的录播软件是录播姬）

**Comment by hihkm** [comment]
你好，可以的话希望可以提供一下出现异常的xml文件，谢谢！

**Comment by lanyuuuu** [comment]
[弹幕xml文件.zip](https://github.com/hihkm/DanmakuFactory/files/9869422/xml.zip)

**Comment by hihkm** [comment]
你好，请在录制的时候勾选`保留弹幕原始数据`，否则弹幕文件不携带礼物的价值相关数据~
![mmexport1666789306101](https://user-images.githubusercontent.com/40973421/198033404-ef79c57c-29e4-483d-9248-351445693c34.png)

**Comment by lanyuuuu** [comment]
刚刚重看了一遍文件，发现录播姬礼物不记录价格了，新版本或许可以按礼物名称来进行屏蔽吗？

**Comment by lanyuuuu** [comment]
好的！感谢您的解答！

**Comment by hihkm** [comment]
你好，请在录制的时候勾选`保留弹幕原始数据`，否则弹幕文件不携带礼物的价值相关数据~
新版本有必要做相关的屏蔽，最近比较忙，重构的时候会考虑~
![mmexport1666789306101](https://user-images.githubusercontent.com/40973421/198033404-ef79c57c-29e4-483d-9248-351445693c34.png)
