### ISSUE TITLE
可否做个芒果tv的弹幕转换

### ISSUE THREAD

**Issue by lwgpshit** [hihkm/DanmakuFactory#3]
原理应该差不多,json格式的,网址：
https://galaxy.bz.mgtv.com/rdbarrage?version=2.0.0&vid=5683459&cid=328724&time=0
后面time是分钟乘以60000

**Comment by hihkm** [comment]
我考虑一下，后续版本可能会悄悄加入读入（可以实现转ass/xml），但输出不一定会做，因为a站也用的json，改调用方法就不是太好。
现在优先完成GUI，考试周也比较忙。请关注下个版本或下下个版本，七月下旬的样子，您也可以留下邮箱，更新之后我发个邮件，感谢支持。

**Comment by lwgpshit** [comment]
ok,我会关注的

**Comment by hihkm** [comment]
抱歉久等了，请查看最新的CLI版本更新

**Comment by 20NE** [comment]
版本：v1.70
運行`DanmakuFactory -o ass "mgtv.ass" -i json  "Downloads/rdbarrage.json"` 失敗，错误信息：
```
WARNING [code rj7]
Incorrect file format, contiune or exit?
NOTE
Could not load file "Downloads/rdbarrage.json" as a json file.
```
"Downloads/rdbarrage.json"文件内容：
```
{"status":0,"msg":"操作成功","seq":"","data":{"next":60000,"interval":60,"items":[{"ids":"6694905896150968584","type":0,"uid":419234108,"content":
...
]}}
```
