### ISSUE TITLE
ASS转XML格式弹幕无法正常读取

### ISSUE THREAD

**Issue by diana52** [hihkm/DanmakuFactory#31]
转换完成后，弹幕显示
`<d p="0,5,11,16777215,,0,NULL,">正片在00:27</d>`
其中：
1.缺少timestamp时间戳，unix时间（好像置0也行，试了下不影响弹幕显示）
2.缺少发送者uid（随便改了下试试，无所谓，NULL也行）
3.缺少row_id用于标记顺序和历史弹幕，没有这个无法读取（这个随机生成应该就可以，但不可以是NULL，试过NULL读不出来）
希望转换功能能完善~
播放软件：弹弹play

**Comment by diana52** [comment]
"<d p="{time},{type},{size},{color},{timestamp},{pool},{uid_crc32},{row_id}"> {Text} <‌/d>”

    <‌!-- time为弹幕在视频里的时间 -->

    <‌!-- type为弹幕类型 -->

    <‌!-- size为字体大小 -->

    <‌!-- color为十进制的RGB颜色（16进制转10进制） -->

    <‌!-- timestamp为弹幕发送时间戳（unix时间戳） -->

    <‌!-- pool为弹幕池 -->

    <‌!-- uid_crc32为发送者uid的crc32 -->

    <‌!-- row_id用于标记顺序和历史弹幕 -->

**Comment by hihkm** [comment]
感谢指出！目前在bililocal上是可用的。但是还没有针对弹弹play做适配，重构后会添加~

**Comment by hihkm** [comment]
已在最新版本修复。
