### ISSUE TITLE
在 macOS 上能用来将 ass 转换成 xml 吗？

### ISSUE THREAD

**Issue by NSFish** [hihkm/DanmakuFactory#32]
你好😀。
我在 macOS 上编译并尝试使用了一下，输入如下
```shell
./DanmakuFactory -o xml "a.xml" -i ass /Users/nsfish/Downloads/a.ass
```
结果并没有生成 xml 文件。输出如下
```shell
DanmakuFactory 1.62 CLI Release by hkm (hkm@tikm.org)
https://github.com/hihkm/DanmakuFactory

Input file(s):
Number|Template     |TimeShift|FileName
     1|ass          |   0.000s|/Users/nsfish/Downloads/a.ass

Output file:
Format|FileName
   xml|a.xml

Loading files...
Loading file "/Users/nsfish/Downloads/a.ass"
[1]    30234 trace trap  ./DanmakuFactory -o xml "a.xml" -i ass /Users/nsfish/Downloads/a.ass
```
a.ass 的内容非常简单，见 
[a.ass.zip](https://github.com/hihkm/DanmakuFactory/files/10199517/a.ass.zip)

Readme 里没有列出 macOS，但我想既然是 C，和在 Linux 下区别应该不大，不知道是不是输入的不对呢？
感谢您的作品。

**Comment by hihkm** [comment]
你好，你的输入是正确的，经过测试此输入文件和命令行在windows和linux下都是能正常工作的。
本项目用 C 编写，并且几乎完全使用C标准库（以前太闲了），理论上不会出现这样的问题。唯一一处系统相关的地方在 main.c 第 17-29 行：
```
#ifdef _WIN32
/* windows下 */
#include <windows.h>
#include <io.h>
#define F_OK 0
#define W_OK 2
#define R_OK 4

#else
/* linux下 */
#include <unistd.h>

#endif
```
但是据我所知 `unistd.h` 在macOS下也是可用的。
从终端的打印来看，应该是在读入ass文件的时候crash了。由于本人没有macOS的环境，对macOS的特性不了解，所以很抱歉目前无法直接调试该问题qwq。

**Comment by hihkm** [comment]
如果您愿意帮忙调试，我会尽可能地提供帮助~

**Comment by NSFish** [comment]
你好。
我尝试用 Xcode 进行了调试，发现问题可能出在这里
```C
#define MARKSTR_SIZE 12

// ...

int readAssFile(ASSFILE *assFile, const char *const fileName)
{
    char mark[MARKSTR_SIZE], lowerMark[MARKSTR_SIZE];
    
    // ...
    while (!feof(fptr))
    {
        /* 读取一行 */
        if (fgets(line, ASS_MAX_LINE_LEN, fptr) == NULL)
        {
            break;
        }
        line[ASS_MAX_LINE_LEN - 1] = '\0';
        if (line[strlen(line)-1] == '\n')
        {
            line[strlen(line)-1] = '\0';
        }
        
        /* 读取标记 */
        ptr = line; 
        strGetLeftPart(mark, &ptr, ':', MARKSTR_SIZE);
        trim(mark);/* 去左右空格 */ 
        toLower(lowerMark, mark);/* 转换为小写 */ 
        // ...
    }
}
```
假设 line 为 "Original Script: B站bilibil弹幕下载生成ASS字幕"，则 mark 应该是 "Original Script"，长度为 15，而 MARKSTR_SIZE 是 12，于是就 Crash 了。。

我把 MARKSTR_SIZE 改为 24，就可以正常使用了。

**Comment by NSFish** [comment]
不过这样一来就让我更困惑了，为什么在 Windows 或者 Linux 上不会 Crash 呢？
我的电脑是 macOS m1，架构是 ARM 64，难道和这个有关？

**Comment by hihkm** [comment]
非常感谢您能抽空帮忙调试！
正如你所说，崩溃的直接原因是`maxLen`无法生效而导致了内存的非法访问。内存非法访问会导致“未定义行为”，该“未定义行为”确实会与平台相关的（~也会和运气有关~），它会受内存分配的策略、内存对齐等方面影响。而 C Runtime 并不会检查该地址是否合法，通常是在硬件访问时发现的。
越界访问程序却能正常运行的可能性有很多，比如虽然越界了，但是访问的是却另一个合法的地址（比如另一个数组）。
估计是这样的原因导致一直没有发现该问题。而这种行为是不可控的，换一个环境，完全不可预知访问的是个什么东西。该问题将会尽快修正！
最后，再次感谢大佬的帮助！

**Comment by hihkm** [comment]
已修复！
