### ISSUE TITLE
日文xml加载出错

### ISSUE THREAD

**Issue by mikudate** [hihkm/DanmakuFactory#4]
WARNING [code rx8]
Incorrect file format, contiune or exit?
NOTE
Could not load file D:\01.xml as a xml file.

[himado](http://himado.in/)下载的xml无法转换
是日文编码的原因？还是程序本身不支持国内弹幕站以外的xml文件？

**Comment by hihkm** [comment]
字串是源文件拷贝的，不存在编码问题。暂不支持国外弹幕站的文件（国内的也支持不完），各种格式太多了，正在考虑做一个用户自定义输入模板的功能，敬请期待后续更新。
如果可以的话希望可以提供一下弹幕文件或者一小段供参考，谢谢！

**Comment by mikudate** [comment]
> 字串是源文件拷贝的，不存在编码问题。暂不支持国外弹幕站的文件（国内的也支持不完），各种格式太多了，正在考虑做一个用户自定义输入模板的功能，敬请期待后续更新。
> 如果可以的话希望可以提供一下弹幕文件或者一小段供参考，谢谢！

[弹幕文件](http://himado.in/?mode=commentgroup&group_id=536133)是这样的

**Comment by hihkm** [comment]
好的，感谢

**Comment by hihkm** [comment]
抱歉久等了，请查看最新的CLI版本更新
