### ISSUE TITLE
我命令你立即将sc时长的逻辑由程序中规定的时间，变为读取xml中的sc元素中的时间！不能再鸽了！

### ISSUE THREAD

**Issue by holwell** [hihkm/DanmakuFactory#42]
感谢建议！目前sc与其他礼物一样以滚动的形式显示在礼物框中。后续会加入更多显示方式。
目前该项目正在重构，目的是提供更多自定义功能和解决一些问题。

_Originally posted by @hihkm in https://github.com/hihkm/DanmakuFactory/issues/24#issuecomment-1150926667_

**Comment by hihkm** [comment]
本来预计是1月末做完的，但是呢未曾想这段时候巨忙，短时间无精力去维护了。
如果要在原基础上改动，这个改动是非常麻烦的，并不是修改一个时间就可以了，用ass做出整个动画非常复杂。
所以嘛，请容许我继续鸽一段时间~（或许你可以提交一个pr）

**Comment by holwell** [comment]
> 本来预计是1月末做完的，但是呢未曾想这段时候巨忙，短时间无精力去维护了。 如果要在原基础上改动，这个改动是非常麻烦的，并不是修改一个时间就可以了，用ass做出整个动画非常复杂。 所以嘛，请容许我继续鸽一段时间~（或许你可以提交一个pr）

别人hihkm项目做得蛮好的，你把他换了干嘛，你让我来？没那个能力知道吧！我选择继续等待大佬更新

**Comment by sieveLau** [comment]
今天试了一下，大佬您的writeass那一部份我是真的改不明白（允悲）。读取xml中的存活时间（比如录播姬的sc元素就有个tag叫time）倒是容易——改动一下gift这个struct加个existTime就能在write里面拿到，readXML中加一行判断key是"time"就设置existTime就好。

但是难点在于现有的messagebox淘汰逻辑是以“msgDuration是一个const”来写的：

`writeAssDanmakuPart()`（`AssFile.c`的第1274行）里面原来用的是MSGLIST（链表）（`AssFile.c`的第1883行）来记录所有存活的msgbox，作者写的时候逻辑是按照一个const的msgDuration来进行淘汰。

虽然在`writeAssDanmakuPart()`里面通过`now->gift->existTime`就可以访问sc元素的存活时间，但是因为SC都是不同金额的，所以不能照用原来的淘汰逻辑。

实现淘汰逻辑的代码实现在1937行，然而我看不懂orz

如果是根据sc元素本身的time来确定消失时间的话，一个是要把MSGLIST的元素淘汰逻辑单独做成一个function来做会比较好（现在的结构真的很难维护也很难看懂），另一个就是动画的问题了。
