### ISSUE TITLE
增加-y参数供无互动脚本使用

### ISSUE THREAD

**Issue by puzzlemoondev** [hihkm/DanmakuFactory#43]
目前如果输出目标已存在会询问是否覆写，对自动化使用不友善。
可否参考其他cli工具增加一个-y的flag，所有互动选项自动yes？

**Comment by hihkm** [comment]
你好，使用 `--ignore-warnings` 参数可以达到此效果。

**Comment by puzzlemoondev** [comment]
感谢回覆，`--help`没有看到这个参数所以困惑了。
