### ISSUE TITLE
linux使用问题

### ISSUE THREAD

**Issue by coldnight9** [hihkm/DanmakuFactory#49]
你好，下载编译包Source code.tar.gz 进行编译后，使用这个命令一直无法转换弹幕，请问这是什么问题呢？
命令为:./DanmakuFactory -o ass "1234.ass" -i xml "1234.xml"   DanmakuFactory目录下有“1234.ass”这个文件
返回报错在下图
![QQ截图20230427040356](https://user-images.githubusercontent.com/80202197/234689757-1f904f4c-45b6-4adc-8231-43ce8625a806.png)

**Comment by hihkm** [comment]
你好，
需要确保DanmakuFactory目录下有输入文件 “1234.**xml**” ，并且需要有写权限。
如果没有问题，请尝试删除 `main.c` 的 `879`-`893`行，可能是这个api有问题~

**Comment by sieveLau** [comment]
> 你好， 需要确保DanmakuFactory目录下有输入文件 “1234.**xml**” ，并且需要有写权限。 如果没有问题，请尝试删除 `main.c` 的 `879`-`893`行，可能是这个api有问题~



_（我的是Archlinux，维护着AUR上的[danmakufactory-git](https://aur.archlinux.org/packages/danmakufactory-git)和[danmakufactory](https://aur.archlinux.org/packages/danmakufactory)两个包，这两个包都是直接拉github源码下来编译的。）_

没有遇到这样的报错，应该不是api问题。

**Comment by coldnight9** [comment]
> > 你好，确保DanmakuFactory目录下有输入文件“1234. **xml** ” ，并且需要有写权限。如果没有问题，请尝试删除的`main.c`-`879`行`893`，可能是这个api有问题~
> 
> _（我是Archlinux，维护着AUR上的[danmakufactory-git](https://aur.archlinux.org/packages/danmakufactory-git)和[danmakufactory](https://aur.archlinux.org/packages/danmakufactory)两个包，这两个包都是直接拉github源码下来编译的。）_
> 
> 没有遇到这样的报错，应该不是api问题。

谢谢您的回答，我把输入和输出文件搞反了

**Comment by coldnight9** [comment]
> 你好， 需要确保DanmakuFactory目录下有输入文件“1234. **xml** ” ，并且需要有写权限。 如果没有问题，请尝试删除`main.c`的`879`-`893`行，可能是这个api有问题~

谢谢您的回答，我把输入和输出文件搞反了
