### ISSUE TITLE
ass转xml的一系列问题

### ISSUE THREAD

**Issue by sxxcb** [hihkm/DanmakuFactory#5]
我使用的的是经过xml转ass的文件，想转回xml，但是网上没有找到相应的软件，现在终于找到了这个。
使用后发现ass转xml后基本弹幕都带有框框，这个框应该是自己发弹幕才有的这个属性，应该是第一次xml转ass后丢失了发送者ID的原因。
能不能修复这个问题，比如在ass转xml时提供模板，手动给所有弹幕增加一个选项，让它不显示框框？

**Comment by hihkm** [comment]
您使用的是什么软件来加载xml呢

**Comment by sxxcb** [comment]
> 您使用的是什么软件来加载xml呢

BiliLocal

**Comment by hihkm** [comment]
啊这，，之前没有注意到这个问题，后续会修复。
临时补救可以用文本编辑器进行文本替换，给原本填id的地方随便填点东西就可以了。
比如将 `,,">` 替换成 `,1,">`
用正则整行替换会更准确一些~

**Comment by hihkm** [comment]
已修复
