### ISSUE TITLE
弹幕合并＋时移

### ISSUE THREAD

**Issue by xialei123456** [hihkm/DanmakuFactory#58]
大佬您好，请问现在支持xml弹幕合并并自动添加时移吗，我使用的是cli版本，并将多个xml按照顺序放在输入文件中国实现了合并，但是好像没有进行时移导致弹幕重叠在了一起

**Comment by hihkm** [comment]
你好，现版本支持时移操作，例子如下：
有两个输入文件： `in1.xml` (偏移 -1 秒) ； `in2.xml` (偏移 3 秒) ，合并之并输出到 `out.ass`：
`DanmakuFactory -o “out.ass” -i “in1.xml” “in2.xml” -t -1.0 3.0`

**Comment by xialei123456** [comment]
> 

好！！感谢大大
