### ISSUE TITLE
能打包个python版吗？

### ISSUE THREAD

**Issue by Heporis** [hihkm/DanmakuFactory#64]
利用git action自动打包发到pypi，方便别的一些项目调用，谢谢！

**Comment by Heporis** [comment]
我看[danmakuC](https://github.com/HFrost0/danmakuC)是C++写的，不是也有python版吗？
好像可以这样搞：https://cloud.tencent.com/developer/news/405436
不过我是看不懂😅

**Comment by Heporis** [comment]
我看[danmakuC](https://github.com/HFrost0/danmakuC)是C++写的，就有python模块，可以直接用pip安装
好像可以这样搞：https://cloud.tencent.com/developer/news/405436
不过我是看不懂😅

**Comment by hihkm** [comment]
这个可以，但是很麻烦，因为当初写的时候就没有过多考虑对外的接口~
目前在用python重写，也可以等我的python版本。
是什么样的需求呢
