### ISSUE TITLE
通过B站录播姬获得的字幕中有emoji符号，用该软件转成ass格式后，使用时会存在部分字幕异常中置。

### ISSUE THREAD

**Issue by YaoHwa** [hihkm/DanmakuFactory#66]
不知道是ass格式对emoji的支持有问题，还是其他地方有问题。我在用PotPlayer播放视频时添加字幕以及用哔哩哔哩投稿工具将字幕压入视频都会异常，删除emoji后会恢复正常。

**Comment by YaoHwa** [comment]
B站录播姬获得的字幕中有emoji符号，使用该软件转成ass格式后，在potplayer中使用会使得部分字幕异常中置。

**Comment by hihkm** [comment]
你好，有没有能复现该问题的xml或ass的弹幕文件呢

**Comment by YaoHwa** [comment]
文件名为“录制……”的xml文件为原文件。
未删除.ass是从原文件转成的ass文件中截取的前十几分钟部分，其中第350行有‘✌’符号，在PotPlayer中播放或者用哔哩哔哩投稿工具将字幕压入视频，都会出现如附件图片中的异常。
删除后进行测试，会恢复正常。
---- Replied Message ----
| From | ***@***.***> |
| Date | 8/6/2023 11:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hihkm/DanmakuFactory] B (Issue #66) |

你好，有没有能复现该问题的xml或ass的弹幕文件呢

**Comment by YaoHwa** [comment]
文件名为“录制……”的xml文件为原文件。
未删除.ass是从原文件转成的ass文件中截取的前十几分钟部分，其中第350行有‘✌’符号，在PotPlayer中播放或者用哔哩哔哩投稿工具将字幕压入视频，都会出现如附件图片中的异常。
删除后进行测试，会恢复正常。


（上一个邮件附件添加错误）
---- Replied Message ----
| From | ***@***.***> |
| Date | 8/6/2023 11:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hihkm/DanmakuFactory] B (Issue #66) |

你好，有没有能复现该问题的xml或ass的弹幕文件呢

**Comment by sieveLau** [comment]
还是看不到附件哦，而且issue标题不能反映内容，建议修改一下

**Comment by YaoHwa** [comment]
> 你好，有没有能复现该问题的xml或ass的弹幕文件呢

文件名为**录制……**的xml文件为原文件。
**未删除.ass**是从原文件转成的ass文件中截取的前十几分钟部分，其中第350行有‘✌’符号，在PotPlayer中播放或者用哔哩哔哩投稿工具将字幕压入视频，都会出现如附件图片中的异常。删除后会恢复正常。
附件地址：[https://www.aliyundrive.com/s/d6ZwiFV63C5](url)

**Comment by YaoHwa** [comment]
> 还是看不到附件哦，而且issue标题不能反映内容，建议修改一下

已修改，谢谢提醒！我第一次使用Github，不太熟悉，误操作了。

**Comment by hihkm** [comment]
![image](https://github.com/hihkm/DanmakuFactory/assets/40973421/5cac8df8-41e7-4782-b497-f35da8ac50fa)
未复现，emoji的支持之前没有出现过什么问题，可以提供更多的信息吗~

**Comment by YaoHwa** [comment]
> ![image](https://user-images.githubusercontent.com/40973421/258654094-5cac8df8-41e7-4782-b497-f35da8ac50fa.png) 未复现，emoji的支持之前没有出现过什么问题，可以提供更多的信息吗~

谢谢了，或许是我设备的问题。

**Comment by sieveLau** [comment]
如果暂时没有问题的话记得关闭issue哦
