### ISSUE TITLE
优化文件读取性能

### ISSUE THREAD

**Issue by lengyanyu258** [hihkm/DanmakuFactory#67]
随着 Gift Combo 功能的实装，我的开发工作也告一段落了。
现在的性能瓶颈在于磁盘 IO 比较费时，读取文件的速度大约为 12 MB/s.

转换一个 41 MiB 大小的 XML 文件大约需用 4 秒，221 MiB 大约需要 21 秒。

主要的耗时部分在于读取，这里有两个文件可供测试：
1. [test1-41MiB.zip](https://github.com/hihkm/DanmakuFactory/files/12296971/test1-41MiB.zip)
2. [test2-221MiB.zip](https://github.com/hihkm/DanmakuFactory/files/12296978/test2-221MiB.zip)

**Comment by renmu123** [comment]
[test-111.zip](https://github.com/user-attachments/files/16195999/test-111.zip)

我使用如下的命令` -i test.xml -o test.ass`进行转换  
我定位到是这个[函数](https://github.com/hihkm/DanmakuFactory/blob/d994828fa3bb39c06e625062faadf5a8850abeaf/XmlFile.c#L297)占用了大部分时间

`readXml()`函数共花费10.37s，单单这个函数花费了9.2s
