### ISSUE TITLE
有关文件名的小bug

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [hihkm/DanmakuFactory#7]
windowsx64,使用guibeta1.51版
在文件名包含♪（已知）或者其他特殊符号的时候执行转换会报错
报错如下:
0---------
输入文件:I:\win rec\GACHIIII\椎名菜羽Official\椎名菜羽Official20210130-160115-【B限】吉他弾唱♪ .xml
输出文件:I:\win rec\GACHIIII\椎名菜羽Official\ass\椎名菜羽Official20210130-160115-【B限】吉他弾唱♪ .ass
信息:命令行程序执行时发生错误

ERROR
No such file.

**Comment by hihkm** [comment]
可能是因为该字符没有对应的gbk编码，win控制台对unicode的支持太差了。建议先改下名字规避一下这些字符，后续我看看有没有办法解决。
