### ISSUE TITLE
cli是否有参数支持指定配置文件？

### ISSUE THREAD

**Issue by renmu123** [hihkm/DanmakuFactory#72]
我最近在制作一款快速压制录播视频的工具，想把这个cli工具集成进去，请问是否有参数支持指定配置文件

**Comment by renmu123** [comment]
如果能支持指定配置文件的话会更加灵活

**Comment by hihkm** [comment]
> 目前是这样的，由于主程序设计的时候，把配置文件写死了——DanmakuFactory可执行程序同目录下的DanmakuFactoryConfig.json——所以可以先执行`DanmakuFactory --save`生成基本的配置文件，然后再直接执行`DanmakuFactory`就会自动读取配置了。
> 
> @hihkm 但是`-c`（`--config`）参数这样的写法其实不太符合常见的cli的功能，或许可以改成有`-c`但是没有指定文件的话就是现在的功能（显示配置），如果指定了文件的话就是读取那个配置文件？

显示配置感觉上比较鸡肋，如果有这种需求可以做成指定配置文件~

**Comment by Heporis** [comment]
顺便添加一个静默执行的参数吧
