### ISSUE TITLE
输入多个xml文件时礼物栏的显示时间错误

### ISSUE THREAD

**Issue by LeonardHalf** [hihkm/DanmakuFactory#75]
[xml.zip](https://github.com/hihkm/DanmakuFactory/files/13389022/xml.zip)
来自第二个xml文件的礼物和sc在左侧礼物栏中显示时长异常的长，在样例中大约会持续约3小时，设置时轴偏移（-t 0 3664.27）后也没有改善
具体的说大概是一个sc发出来后几个小时都不会在ass文件中消失，我查看ass文件发现似乎部分sc在ass文件中出现了数百行dialogue，比如文件末尾那个sc
这是生成的ass文件和我的配置文件
[20231116.ass.zip](https://github.com/hihkm/DanmakuFactory/files/13389114/20231116.ass.zip)
[DanmakuFactoryConfig.json](https://github.com/hihkm/DanmakuFactory/files/13389040/DanmakuFactoryConfig.json)

**Comment by lengyanyu258** [comment]
最新版的程序中貌似已经消除了这样的 bug（并且还会将相邻时间段合并，不再让 SC 或礼物的 Dialogue 冗余出现上百行，参见： 41cb756af955cf5a390c75eb86df8da98786b41b 和 78ca6bfa9a51d7a88b314f953a5f97cb7467440c）
