### ISSUE TITLE
1.70版xml转ass后，滚动弹幕会出现整体下移的情况

### ISSUE THREAD

**Issue by Lain0v0** [hihkm/DanmakuFactory#76]
请问一下
排除法测试了很久，powershell和cmd都测试运行过，也试过用批处理，文字编码也固定了
出现规律不详
一些xml文件，将输出文件名的中文全替换成英文后恢复正常
又有某几个文件，不管怎么修改都还是出现整体下移，但是，使用1.63的GUI版本转换是正常的
喜欢1.70的自定义字体和能带小数点的描边效果
![image](https://github.com/hihkm/DanmakuFactory/assets/53465954/dbb68f0c-7848-464d-8505-c19462958b79)
![image](https://github.com/hihkm/DanmakuFactory/assets/53465954/470c110f-1aab-43ba-a1a5-1709c1337a1e)
参数设置如下：
    "resolution": [632, 400],
    "scrolltime": 12.000000,
    "fixtime": 5.000000,
    "density": 0,
    "fontname": "SimHei",
    "fontsize": 14,
    "opacity": 180,
    "outline": 0.5,
    "shadow": 0.0,
    "displayArea": 1.000000,
    "scrollArea": 1.000000,
    "bold": true,
    "showUsernames": false,
    "showMsgbox": false,
    "msgboxSize": [500, 1080],
    "msgboxPos": [20, 0],
    "msgboxFontsize": 38,
    "msgboxDuration": 0.00,
    "giftMinPrice": 0.00,
    "giftMergeTolerance": 0.00,
    "blockmode": [],
    "statmode": []

**Comment by lengyanyu258** [comment]
提供一下出现问题的弹幕文件~

有可能是不同程序采用的 `"resolution": [632, 400]` 设置不同，导致输出的弹幕范围高度低于实际视频高度

**Comment by Lain0v0** [comment]
> 提供一下出现问题的弹幕文件~
> 
> 有可能是不同程序采用的 `"resolution": [632, 400]` 设置不同，导致输出的弹幕范围高度低于实际视频高度

[问题弹幕.zip](https://github.com/hihkm/DanmakuFactory/files/13800265/default.zip)
第1个是偶尔会出现便宜偶尔正常，第2个是必定出现偏移

**Comment by lengyanyu258** [comment]
我用 DanmakuFactory1.70_Release_CLI 和根据最新提交编译出来的版本（[DanmakuFactory.zip](https://github.com/hihkm/DanmakuFactory/files/13392902/DanmakuFactory.zip)）测试均未复现问题：
[[武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣.zip](https://github.com/hihkm/DanmakuFactory/files/13800537/05.zip)
可以看到两者第一条弹幕的纵坐标是从 3、5（均靠近 0，即最顶部）开始的。
我猜测可能是使用的视频播放软件有问题？（试试 VLC 播放器？）

**Comment by Lain0v0** [comment]
> 我用 DanmakuFactory1.70_Release_CLI 和根据最新提交编译出来的版本（[DanmakuFactory.zip](https://github.com/hihkm/DanmakuFactory/files/13392902/DanmakuFactory.zip)）测试均未复现问题： [[武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣.zip](https://github.com/hihkm/DanmakuFactory/files/13800537/05.zip)
> 
> ```
> file name: [武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣 - DanmakuFactory1.70_Release_CLI.ass
> line 21: Dialogue: 0,0:00:00.00,0:00:12.00,R2L,,0000,0000,0000,,{\move(663,3,-31,3)\q2\fs14}观众2你好
> 其中 \move(663,3,-31,3) 的 3 是该条弹幕的纵坐标
> 
> file name: [武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣 - DanmakuFactory.ass
> line 24: Dialogue: 0,0:00:00.00,0:00:12.00,R2L,,0000,0000,0000,,{\move(661,5,-29,5)}观众2你好
> 其中 \move(661,5,-29,5) 的 5 是该条弹幕的纵坐标
> ```
> 
> 可以看到两者第一条弹幕的纵坐标均是从靠近 0（即最顶部）的地方开始的，并未出现下移的情况。
> 
> ```powershell
> # 执行的命令
> .\DanmakuFactory_REL1.70CLI.exe -o ass ".\[武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣.ass" -i xml ".\[武林外传].05.展红纹千里定扒手.郭芙蓉一心迷盗圣.xml"
> # 参数设置保存在同目录下的 DanmakuFactoryConfig.json 文件中
> ```
> 
> 我猜测可能是使用的视频播放软件有问题？（试试 VLC 播放器？）
> 
> 还有，预祝元旦快乐啊~

非常感谢！我尝试用你的命令，在第五集上转换后是正常的，但是其他的又会出现错误。
可以确定不是播放器的问题，我在ipad上以及emby上使用均出现相同问题。
我们之间使用命令的区别是，我没有指定文件名前的ass和xml，以及用了批处理。
我尽量控制变量测试了一下，还是会出现问题，某几集正常后，其他几集又不正常了，相关文件我都放压缩包了~
也祝你跨年快乐！~
[弹幕文件.zip](https://github.com/hihkm/DanmakuFactory/files/13800885/default.zip)
[批处理文件.zip](https://github.com/hihkm/DanmakuFactory/files/13800886/default.zip)
[出问题的ass.zip](https://github.com/hihkm/DanmakuFactory/files/13800887/ass.zip)
[测试视频与配置文件.zip](https://github.com/hihkm/DanmakuFactory/files/13800888/default.zip)
