### ISSUE TITLE
【bug】--statmode HISTOGRAM  高能进度条不正常 ​

### ISSUE THREAD

**Issue by specked2527** [hihkm/DanmakuFactory#79]
![20240521-230946](https://github.com/hihkm/DanmakuFactory/assets/124735279/a7895c16-ee0a-4027-8622-b05defd8f6df)
[i .xml o .ass r 720 1280.zip](https://github.com/hihkm/DanmakuFactory/files/15391823/i.xml.o.ass.r.720.1280.zip)

**Comment by specked2527** [comment]
DanmakuFactory1.70_Release_CLI> .\d -i "录制-27279805-20240520-210304-017-封面内容一样，不一样你捶我.xml" -o 1.ass --statmode HISTOGRAM -r 720 1280



```
Input file(s):
Number|Template     |TimeShift|FileName
     1|xml          |   0.000s|录制-27279805-20240520-210304-017-封面内容一样，不一样你捶我.xml

Output file:
Format|FileName
   ass|1.ass

Loading files...
Loading file "录制-27279805-20240520-210304-017-封面内容一样，不一样你捶我.xml"

File Loading Complete.. Danmaku Pool: 1072

Sorting...

Writting file "1.ass"...

Done!
```

**Comment by lengyanyu258** [comment]
> 这个问题比较尴尬，统计表是四年前最开始就有的功能，实现写的比较死，而礼物弹幕是后来追加的，为了防止统计出问题（当时觉得应该也没人用这玩意儿），所以只是简单地做了一个拦截，但凡存在一条不是正常的弹幕统计表就不会生成。
> 因为在重构，所以不打算对当前版本做较大的改动了，希望能理解~

_Originally posted by @hihkm in https://github.com/hihkm/DanmakuFactory/issues/33#issuecomment-1345573589_

也就是说，目前的功能来讲，只有当 `xml` 文件只包含标签为 `d` 的正常弹幕时，才会去显示弹幕统计表。

具体来说，需要将你上传的 `xml` 文件中，第 `472` 行标签为 `guard` 的弹幕删掉，即可生成统计图表。

**Comment by specked2527** [comment]
> > 这个问题比较尴尬，统计表是四年前最开始就有的功能，实现写的比较死，而礼物弹幕是后来追加的，为了防止统计出问题（当时觉得应该也没人用这玩意儿），所以只是简单地做了一个拦截，但凡存在一条不是正常的弹幕统计表就不会生成。
> > 因为在重构，所以不打算对当前版本做较大的改动了，希望能理解~
> 
> _Originally posted by @hihkm in [#33 (comment)](https://github.com/hihkm/DanmakuFactory/issues/33#issuecomment-1345573589)_
> 
> 也就是说，目前的功能来讲，只有当 `xml` 文件只包含标签为 `d` 的正常弹幕时，才会去显示弹幕统计表。
> 
> 具体来说，需要将你上传的 `xml` 文件中，第 `472` 行标签为 `guard` 的弹幕删掉，即可生成统计图表。



> > 这个问题比较尴尬，统计表是四年前最开始就有的功能，实现写的比较死，而礼物弹幕是后来追加的，为了防止统计出问题（当时觉得应该也没人用这玩意儿），所以只是简单地做了一个拦截，但凡存在一条不是正常的弹幕统计表就不会生成。
> > 因为在重构，所以不打算对当前版本做较大的改动了，希望能理解~
> 
> _Originally posted by @hihkm in [#33 (comment)](https://github.com/hihkm/DanmakuFactory/issues/33#issuecomment-1345573589)_
> 
> 也就是说，目前的功能来讲，只有当 `xml` 文件只包含标签为 `d` 的正常弹幕时，才会去显示弹幕统计表。
> 
> 具体来说，需要将你上传的 `xml` 文件中，第 `472` 行标签为 `guard` 的弹幕删掉，即可生成统计图表。

但这没解释1.63gui可以生成直立方，虽然没有统计表，我也没有删除`472` 行标签为 `guard` 的弹幕
![vlcsnap-2024-05-31-20h27m35s300_看图王](https://github.com/hihkm/DanmakuFactory/assets/124735279/2ab098d4-7da9-437b-a412-09764c0fec9e)
统计表无所谓，但是这个高能进度条，是我唯一能找到能用的了，切片时比在Audacity里看声波疯狂点击 和视频随机拖进度条要好多了
大v高能可以看录播站和弹幕库，小v就不行了，无法添加。


https://github.com/valkjsaaa/danmaku_tools/issues/15
https://github.com/lihaohong6/bilibili-tools/issues/2
https://github.com/SennriSyunnga/Video-editing-auxiliary-tool-based-on-barrage-analysis-/issues/2
