### ISSUE TITLE
特殊弹幕字符在xml未转义导致无法被解析

### ISSUE THREAD

**Issue by Zhangsq37** [hihkm/DanmakuFactory#84]
开发者你好，
使用时偶然发现当弹幕包含<kbd><</kbd>、<kbd>&</kbd>特殊字符时输出的xml弹幕未转义，导致弹幕无法被解析；且不排除弹幕存在诸如<code>#include<stdio.h></code>等特殊情况导致弹幕无法解析

**Comment by lengyanyu258** [comment]
已处理：#61
请使用最新版（需自行编译……）
