### ISSUE TITLE
自定义模板如何设定？

### ISSUE THREAD

**Issue by leecoooo** [hihkm/DanmakuFactory#9]
能不能详细说说？

**Comment by hihkm** [comment]
在Releases中cli版本的压缩包中有详细的说明文档 [https://github.com/hihkm/DanmakuFactory/releases/download/1.51/DanmakuFactory_win_1.51_CLI_Beta_64.zip](1.51_CLI)
或者可以留下邮箱，我给你发一份

**Comment by leecoooo** [comment]
看到了，感谢说明
