### ISSUE TITLE
请问芒果tv的xml弹幕文件转为ass后，在potplayer里播放会有抖动有办法解决吗？

### ISSUE THREAD

**Issue by zzzop** [hihkm/DanmakuFactory#90]
就是弹幕从右往左飘的时候卡卡的
[https://www.mgtv.com/b/666692/21482957.html?fpa=8&fpt=1&lastp=v_play&ftl=1](url)

是设置的问题吗，用的默认设置
或者有其他播放器推荐吗

**Comment by lengyanyu258** [comment]
1. 试一试 `VLC` 播放器，在 PowerShell 中输入：

    ```powershell
    winget install VideoLAN.VLC
    ```

    或者是采用其它方式安装。

2. 试一下 `MPC-BE` 播放器，在 PowerShell 中输入：

    ```powershell
    winget install MPC-BE.MPC-BE
    # 或者是
    winget install 9PD88QB3BGKN
    ```

    或者是采用其它方式安装。

    **注意**，不要使用它内置的字幕渲染器，而是去下载安装 [XySubFilter](https://github.com/pinterf/xy-VSFilter/releases/latest) 字幕渲染器，并在 `查看 -> 选项 -> 字幕 -> 字幕渲染器` 中选择使用该字幕渲染器。

3. 字幕渲染卡顿也有可能是电脑 CPU 或 内存 资源不足导致的，可以关闭浏览器或其它占用 CPU、内存 资源的程序，以保证播放器不会因为 CPU 资源不足而导致字幕渲染发生卡顿的现象。
